### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by wasifali** [UniversalDataTool/react-image-annotate#106]
I'm trying to use this package and exactly copy pasting the demo code it is giving me the following error, I have made sure that this isn't an issue with my code it's something in the package.
![error](https://user-images.githubusercontent.com/15184858/96714405-8a000000-13bb-11eb-8562-79b6da1d16c4.png)

Code Snippet I'm using,

```
import React from 'react';
import ReactImageAnnotate from "react-image-annotate";

const VerificationPage = (props) => {
  return(
    <ReactImageAnnotate
      images={[
        {
          src: "https://placekitten.com/408/287",
          name: "Image 1",
          regions: []
        }
      ]}
    />);
}

export default VerificationPage;
```

Versions:
```
{
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-helmet": "^6.1.0",
    "react-image-annotate": "1.7.4"
}
```

**Comment by hoangpmhe130495** [comment]
Yes, I have the same error. How to fix ?

**Comment by roychowd** [comment]
I resolved it by updating the react, react-dom. and react-image-annotate versions: 

```javascript
{
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-image-annotate": "1.7.1"
}
```

Hope this helps!
