### ISSUE TITLE
Using the component oustide of React - Tools do not work ? 

### ISSUE THREAD

**Issue by BernhardGlueck** [UniversalDataTool/react-image-annotate#109]
Hi !

I am trying to integrate this component in a larger non React based web application.
I have built/bundled a wrapper module using WebPack and ReactDOM

Everything seems ok, the ui shows up , but drawing anything does not work ( nothing happens when selecting a drawing tool and clicking in the image ) pan/zoom also does not work. 
There are no build or runtime errors reported..

Any ideas what this could be ? 

Here are the relevant files:

Wrapper module:

```javascript
import Annotator from 'react-image-annotate'
import React from 'react'
import ReactDOM from 'react-dom'

const nodes = [];

export function mount(
    props, 
    elementId,
    callback) {
  
    const reactElement = React.createElement(Annotator, props, null);
    const targetNode = document.getElementById(elementId);
    ReactDOM.render(reactElement, targetNode, callback);
    nodes.push(targetNode);
    return reactElement;
}
```
Html ( Just for testing out, not the real app )
```html
<html>
    <head>
        <style>
            @import url("https://rsms.me/inter/inter.css");
        </style>
    </head>
    <body>

        <div id="mount-point">

        </div>

        <script src="react-annotate.js"></script>
        <script>
            ReactAnnotate.mount({
                regionClsList: ["Alpha", "Beta", "Charlie", "Delta"],
                regionTagList: ["tag1", "tag2", "tag3"],
                images:[
                {
                    src: "https://placekitten.com/408/287",
                    name: "Image 1",
                    regions: []
                }
                ],
                onExit: function(state) {
                    alert('Save clicked');
                }
            },'mount-point')
        </script>
    </body>
</html>
```

Webpack config
```
module.exports = {
    entry : './src/index.js',
    output: {
        filename: 'react-annotate.js',
        libraryTarget: 'assign',
        library: 'ReactAnnotate'
    },
    devServer: {
        contentBase: './dist',
        port:  9000,
        injectClient : false
    },
    resolve: {
        fallback: { "path": require.resolve("path-browserify") }
    }
  };
```
package.json
```
{
  "name": "react-annotate",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "webpack --watch",
    "start": "webpack serve",
    "build": "webpack"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "path-browserify": "^1.0.1",
    "react-dom": "^17.0.1",
    "react-image-annotate": "^1.7.4"
  },
  "devDependencies": {
    "webpack": "^5.3.2",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
  }
}
```

**Comment by seveibar** [comment]
hey @BernhardGlueck, thanks for reporting, this is the right place to debug this.

Do you have tine to set up a code sandbox? that would make it easier for us to poke at it

**Comment by BernhardGlueck** [comment]
I have setup a basic sandbox however, i can't get the sample to work there at all ... 
https://codesandbox.io/s/reverent-stallman-znm86?file=/src/index.js

**Comment by philcunliffe** [comment]
Experiencing something similar, we can seemingly force a reproduction by removing <!DOCTYPE html> from the top of our index file

**Comment by BernhardGlueck** [comment]
Sorry what do you mean with "force" a reproduction ? Do you mean that removing the DocType forces the same issue to happen in a standard react app ? ( as opposed to me running it within another app via ReactDOM ? )

**Comment by BernhardGlueck** [comment]
Holy smokes ... that was it.. I had just draftet a quick html file for testing without concern for its structure.

Adding the correct DocType <!DOCTYPE html> seems to fix all issues ....

**Comment by philcunliffe** [comment]
Glad I could help, seems that something about "Quirks" mode is breaking the application
