### ISSUE TITLE
Images state doens't update

### ISSUE THREAD

**Issue by andreehultgren** [UniversalDataTool/react-image-annotate#64]
When updating state of parent component, (changing the set of images and/or the current image). If the new selected image is not a part of the initial set of images, it wont work.

Fix: Make images more dynamic. If images are changed in props, update in the state of the tool.

**Comment by andreehultgren** [comment]
A temporary fix is changing key and thus recreating the component, but it would be way nicer if the image state would update automatically

**Comment by seveibar** [comment]
Good feature/fix request. Will be easier to complete when/if we refactor to recoil, but this is simple enough i think it could be done sooner. Not going to grab myself just set if someone else wants to take a stab at it.
