### ISSUE TITLE
Unable to load local stored images

### ISSUE THREAD

**Issue by vijaylincod** [UniversalDataTool/react-image-annotate#88]
I am working on project where user upload a image zip file and it will get extracted in local. I want to render those extracted images.

Thanks.

**Comment by seveibar** [comment]
Hey @vijaylincod! Thanks for sharing your use case. What happens when you try to import the extracted directory of images with the desktop app? You should be able to do it from `Samples > Import > Files from Directory`

**Comment by vijaylincod** [comment]
Thanks for quick reply. Right now requirement is to create a React App

**Comment by seveibar** [comment]
Web security prevents us from opening local files, you'll need to proxy the files through a server. It's very annoying but "file://" urls simply won't work in a browser

**Comment by vijaylincod** [comment]
Yes correct! So what we are doing. if user uploads a zip file of images it will get extracted and those are serve via nginx and response will "http://localhost/imge.jpg". now we can render

**Comment by seveibar** [comment]
thanks for sharing!
