### ISSUE TITLE
Getting warning in browser console

### ISSUE THREAD

**Issue by deepmistri** [UniversalDataTool/react-image-annotate#96]
When I'm uploading an image I'm getting a warning like  'Each child in a list should have a unique "key" prop.'
can you please help me?

![image](https://user-images.githubusercontent.com/62154851/93479837-69570d00-f91a-11ea-80bf-01a3433afe83.png)

**Comment by canberkakartuna** [comment]
@deepmistri I am getting same problem how did you solve this issue? Thanks.
